# Generated by Django 5.0.6 on 2024-07-02 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custs', to='customers.customer'),
        ),
    ]
