# Generated by Django 5.0.6 on 2024-07-02 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_business_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biz', to='customers.customer'),
        ),
    ]
